In [46]:
from sympleq.core.symmetries import pauli_reduce, min_qudit_clifford_symmetry, qudit_cost, find_clifford_symmetries
from sympleq.models.fermionic_chain import fermionic_chain_hamiltonian
from sympleq.core.circuits.gate_decomposition_to_circuit import gate_to_circuit
import numpy as np
import time

In [47]:
n = 16
J = 1
V = 2
D = 1
D_vec = np.random.uniform(-D/2, D/2, size=n)
periodic = False
H = fermionic_chain_hamiltonian(n, J, V, D_vec, periodic=periodic)
h_red, conditioned_hamiltonians, C_F, phases = pauli_reduce(H)

print(conditioned_hamiltonians[0])
# C_F.show()


(0.6116460408078399+0j) |x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z1 | 0 
(1.188032953270386+0j)  |x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z1 x0z0 | 0 
(0.5+0j)                |x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z1 x0z1 | 0 
(1.0817375721480003+0j) |x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z1 x0z0 x0z0 | 0 
(0.5+0j)                |x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z1 x0z1 x0z0 | 0 
(1.1472925873601987+0j) |x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z1 x0z0 x0z0 x0z0 | 0 
(0.5+0j)                |x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z1 x0z1 x0z0 x0z0 | 0 
(1.0716332881661494+0j) |x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z1 x0z0 x0z0 x0z0 x0z0 | 0 
(0.5+0j)                |x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 x0z1 x0z1 x0z0 x0z0 x0z0 | 0 
(1.169684415209788+0j)  |x0z0 x0z0 x0z0 x0z0 x0z0 x0z0 

In [48]:
H_next = conditioned_hamiltonians[0]

F, S, T = min_qudit_clifford_symmetry(H_next)
assert H_next.to_standard_form() == F.act(H_next).to_standard_form()

Lmin_star (theory half-dim): 1
Block sizes: [4, 4, 4, 4, 4, 4, 4, 2] Q_alg: 2


In [49]:
print(F.symplectic)
print(qudit_cost(S))
print(H_next.n_qudits())

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0

In [55]:
Fs = find_clifford_symmetries(H, num_symmetries=10)

print(len(Fs))
# for f in Fs:
#     print(f.symplectic)


1
