In [1]:
from sympleq.core.symmetries import pauli_reduce, min_qudit_clifford_symmetry, qudit_cost
from sympleq.models.fermionic_chain import fermionic_chain_hamiltonian
from sympleq.core.circuits.gate_decomposition_to_circuit import gate_to_circuit
import numpy as np
import time

In [21]:
n = 3
J = 1
V = 2
D = 1
D_vec = np.random.uniform(-D/2, D/2, size=n)
periodic = False
H = fermionic_chain_hamiltonian(n, J, V, D_vec, periodic=periodic)

print(H)


(0.3023577728021352+0j)|x0z0 x0z0 x0z1 | 0 
(0.9365810805495666+0j)|x0z0 x0z1 x0z0 | 0 
(0.5+0j)               |x0z0 x0z1 x0z1 | 0 
(0.6879835852958224+0j)|x0z1 x0z0 x0z0 | 0 
(0.5+0j)               |x0z1 x0z1 x0z0 | 0 
(-0.5+0j)              |x0z0 x1z0 x1z0 | 0 
(-0.5+0j)              |x1z0 x1z0 x0z0 | 0 
(-0.5+0j)              |x0z0 x1z1 x1z1 | 2 
(-0.5+0j)              |x1z1 x1z1 x0z0 | 2 



In [22]:
F, S, T = min_qudit_clifford_symmetry(H)
assert H.to_standard_form() == F.act(H).to_standard_form()

Lmin_star (theory half-dim): 2
Block sizes: [4, 2] Q_alg: 2


In [23]:
print(F.symplectic)
print(qudit_cost(F))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [1 0 0 1 0 0]
 [0 1 0 0 1 0]
 [0 0 1 0 0 1]]
1
