In [1]:
import time
from sympleq.models.toric_code import ToricCode
from sympleq.core.circuits import SWAP
from sympleq.core.symmetries.clifford import find_clifford_symmetries, qudit_cost, min_qudit_clifford_symmetry
from sympleq.core.symmetries.clifford import qudit_cost
from sympleq.core.circuits import gate_to_circuit
from sympleq.core.circuits import Circuit
import numpy as np


In [11]:
Nx = 2
Ny = 4
periodic = False
c_x = 1.
c_z = 0.5
c_g = 0.1

TC = ToricCode(Nx, Ny, c_x, c_z, c_g, periodic)
H_tc = TC.hamiltonian()
print(H_tc.n_qudits())

start_time = time.time()
F, S, T = min_qudit_clifford_symmetry(H_tc)
end_time = time.time()
assert H_tc.to_standard_form() == F.act(H_tc).to_standard_form()
print(f"Found symmetry in {end_time - start_time} seconds")
print("Qudit cost is ", qudit_cost(S))


10
Lmin_star (theory half-dim): 1
Block sizes: [4, 4, 4, 2, 2, 2, 2] Q_alg: 2
Found symmetry in 1216.8288006782532 seconds
Qudit cost is  2


In [ ]:
print(F.symplectic)  # 3, 3

[[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 1 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 1 0 1 1 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0]
 [1 1 1 1 1 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 1 0 1 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 0 0]
 [1 1 1 1 0 0 1 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [0 0 1 0 1 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 1 0 1 1 0 1 0 1 0 0 1 0

In [ ]:
print(F.symplectic)  # 2, 2


[[0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 1 0]
 [1 0 0 1 0 0 0 1]
 [0 0 1 1 1 0 0 0]
 [0 1 1 0 0 1 0 0]]


In [ ]:
[[0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 1 0 0 0 0 1 0]
 [1 0 0 1 0 0 0 1]
 [0 0 1 1 1 0 0 0]
 [0 1 1 0 0 1 0 0]]